### ISSUE TITLE
Automate flow for publishing formulas

### ISSUE THREAD

**Issue by glooms** [qlik-oss/homebrew-taps#2]
It would be nice to automate the process of publishing formulas so that we can from `corectl` open a PR and then generate bottles for both linux and mac. (At the very least mac.)

The automation must do at least the first of:

- [ ] Create PR when there is a new corectl release containing updated formula
- [ ] Create new bottles based on the updated formula

Who will heed the call for a mighty dev-ops wizard? :pray:

**Comment by wennmo** [comment]
We will use `goreleaser` for publishing a new formula for corectl when a release is made.

https://github.com/qlik-oss/corectl/pull/339

**Comment by wennmo** [comment]
Closing issue since the publishing of the formula will be handled in the `corectl` CI pipeline
